version: "3.5"
services:

  web:
    image: node:10
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8080:8080
    command: bash -c "yarn && yarn start"
